"use client";
import { useEffect,useMemo,useState } from 'react';
import { ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,Clock3,ExternalLink,FlaskConical,History,Menu,Play,RefreshCw,Save,Search,ShieldCheck,Swords,X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from '@/components/ui/sheet';
import { Textarea } from '@/components/ui/textarea';

type Source={id:string;title:string;publisher:string;url:string;dateLabel:string;fact:string;implication:string;limitation:string};
type Experiment={title:string;design:string;measure:string;stop:string};
type Opportunity={id:string;title:string;who:string;proposition:string;support:string;challenge:string;unknown:string;sourceIds:string[];experiment:Experiment;priority?:string;substitutes?:string;advance?:string;scenario?:{move:string;response:string;effect:string}};
type Investigation={updatedAt:string;sources:Source[];opportunities:Opportunity[];revisions:{before:string;after:string;reason:string;sourceIds:string[]}[];missionResults:{missionId:string;answer:string;sourceIds:string[]}[]};
type RecordItem={id:string;kind:string;data:any;updated_at:string};
const featured=['bundle','fresh','dental'];
const demoSteps=['question','bundle','fresh','dental','history'] as const;
const copy:{[key:string]:Partial<Opportunity>}={
 bundle:{priority:'Hold proposed priority',substitutes:'The same recipes purchased separately or an existing assortment.',advance:'Advance when a prospectively agreed minimum improvement in paid repeat or incremental contribution is met.',scenario:{move:'A competing brand copies the assortment and discounts it.',response:'Compare selection usefulness, serving guidance and replenishment—not novelty alone.',effect:'Price pressure removes any presumed assortment advantage. Priority remains held until repeat and incrementality are observed.'}},
 fresh:{priority:'Keep in the comparison',substitutes:'Incumbent fresh products, CESAR and JustFoodForDogs toppers, and the household’s current routine.',advance:'Advance when paid repeat and contribution meet thresholds set before launch at feasible channel costs.',scenario:{move:'An established fresh brand offers a smaller serving at the same daily price as our pantry add-on.',response:'Test a useful difference in serving, waste or convenience at matched feeding budgets.',effect:'Format alone no longer differentiates the offer. The matched-budget comparison becomes the proposed research priority.'}},
 dental:{priority:'Hold until substantiation plan',substitutes:'The closest VOHC-accepted incumbent for the intended claim and serving size.',advance:'Advance when this product supports its own claim and meets choice and contribution thresholds set before launch.',scenario:{move:'The incumbent matches price and emphasizes its existing accepted evidence.',response:'Specify a measurable use or performance advantage, then test whether it matters in paid choice.',effect:'The incumbent retains the evidence advantage. Advancement remains held pending substantiation and a meaningful difference.'}},
 pantry:{priority:'Retain in full comparison',substitutes:'Existing pantry meals and toppers, partial-ration fresh, and current feeding routines.'}
};
const scenarioChoices={bundle:['Copies bundle + discounts','Matches assortment','No response'],fresh:['Matches daily price','Expands distribution','No response'],dental:['Matches price + cites evidence','Adds promotion','No response'],pantry:['Matches format + discounts','Expands assortment','No response']};
const fmt=(d:string)=>new Date(d.length===10?d+'T12:00:00Z':d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});

export default function DecisionLab({baseline,investigation}:{baseline:any;investigation:Investigation}){
 const [area,setArea]=useState('home'),[selected,setSelected]=useState('bundle'),[source,setSource]=useState<Source|null>(null),[records,setRecords]=useState<RecordItem[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [demo,setDemo]=useState<number|null>(null),[scenario,setScenario]=useState<Record<string,string>>({}),[question,setQuestion]=useState('What evidence would distinguish incremental demand from repackaged existing purchases?'),[context,setContext]=useState(''),[connected,setConnected]=useState(false),[draft,setDraft]=useState<Experiment|null>(null);
 const opportunities=useMemo(()=>investigation.opportunities.map(o=>{const saved=records.find(r=>r.kind==='experiment'&&r.id===o.id);return {...o,...copy[o.id],experiment:{...o.experiment,...saved?.data}}}),[investigation,records]);
 const current=opportunities.find(o=>o.id===selected)||opportunities[0]; const actualRun=baseline.runs[0]; const demoOn=demo!==null;
 async function reload(){try{const r=await fetch('/api/workspace',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(d.records);}catch(e){setError(e instanceof Error?e.message:'Saved work unavailable.');}}
 useEffect(()=>{void reload();fetch('/api/investigate').then(r=>r.json()).then(d=>setConnected(!!d.connected)).catch(()=>{});},[]);
 async function save(kind:string,id:string,data:any){const prior=records.find(r=>r.kind===kind&&r.id===id);const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id,data,expectedUpdatedAt:prior?.updated_at||null})}),d=await r.json();if(!r.ok)throw new Error(d.error);setRecords(p=>[d.record,...p.filter(x=>!(x.kind===kind&&x.id===id))]);setNotice('Saved to your private workspace.');}
 function openOpportunity(id:string){setSelected(id);setArea('opportunities');setDraft(null);window.history.replaceState(null,'',`/?opportunity=${id}`);}
 useEffect(()=>{const id=new URLSearchParams(location.search).get('opportunity');if(id&&opportunities.some(o=>o.id===id))openOpportunity(id);},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const sources=(ids:string[])=>ids.map(id=>investigation.sources.find(s=>s.id===id)).filter(Boolean) as Source[];
 function startDemo(){setDemo(0);setArea('home');setSelected('bundle');}
 function goDemo(n:number){setDemo(n);if(n===0)setArea('home');else if(n<4){setSelected(demoSteps[n]);setArea('opportunities');}else setArea('history');}
 const nav=[['home','Overview'],['opportunities','Opportunities'],['evidence','Evidence'],['scenarios','Competitive scenarios'],['experiments','Experiments'],['history','Research history']];
 return <div className="engine-shell"><a className="lab-skip" href="#main">Skip to content</a>{demoOn&&<div className="demo-ribbon"><strong>Demo · illustrative scenarios</strong><span>60 pages reviewed · 7 signals added · Illustrative demo</span><button onClick={()=>setDemo(null)}>Exit demo</button></div>}
 <header className="engine-header"><a href="/" className="engine-brand">PULSE <i/> <b>Insight Engine</b></a><nav aria-label="Primary navigation">{nav.map(([id,label])=><button key={id} className={area===id?'active':''} onClick={()=>setArea(id)}>{label}</button>)}<a href="/signals">Evidence library <ExternalLink size={13}/></a></nav><button className="mobile-menu" aria-label="Show navigation"><Menu/></button></header>
 <main id="main">
 {area==='home'&&<><section className="hero"><div><span className="eyebrow">US PET FOOD · RECORDED RESEARCH</span><h1>What should we learn<br/>before we choose?</h1><p className="question">What opportunities are emerging in pet food—and what evidence would change our choice?</p><div className="hero-actions"><Button onClick={()=>setArea('opportunities')}>Explore opportunities <ArrowRight/></Button><Button variant="outline" onClick={startDemo}><Play/> Start demo</Button></div></div><aside><span>PROPOSED RESEARCH PRIORITY</span><h2>Compare fresh and pantry at the same feeding budget.</h2><p><b>Why now:</b> incumbent fresh volume strengthened purchasing evidence while pantry substitutes already exist.</p><p><b>Principal uncertainty:</b> whether paid repeat and contribution survive feasible prices, displaced purchases and route costs.</p></aside></section>
 <section className="changed"><div><span>WHAT CHANGED · {fmt(actualRun.date)}</span><h2>New activity. Decisions held.</h2></div><p><b>11 readable pages reviewed · 2 signals added.</b> Fancy Feast adds a cat discovery route; a Fi recall adds a supplier-control check. Neither changed recorded priorities.</p><button onClick={()=>setArea('history')}>Review the run <ArrowRight/></button></section>
 <section className="featured"><div className="section-head"><span>THREE DEVELOPED EXAMPLES</span><h2>Different evidence. The same decision discipline.</h2><p>Sequence is for the walkthrough—not an investment ranking.</p></div><div className="cards">{featured.map((id,i)=>{const o=opportunities.find(x=>x.id===id)!;return <article key={id}><span>0{i+1} · {o.priority}</span><h3>{o.title}</h3><p>{o.proposition}</p><dl><dt>Strongest evidence</dt><dd>{o.support}</dd><dt>Largest challenge</dt><dd>{o.challenge}</dd><dt>Next test</dt><dd>{o.experiment.title}</dd></dl><button onClick={()=>openOpportunity(id)}>Open decision <ArrowRight/></button></article>})}</div><button className="all-link" onClick={()=>openOpportunity('pantry')}>View all four opportunities, including pantry <ArrowRight/></button></section></>}
 {area==='opportunities'&&<section className="workspace"><aside className="op-list"><span>OPPORTUNITIES · ALL FOUR</span>{opportunities.map(o=><button className={selected===o.id?'active':''} onClick={()=>openOpportunity(o.id)} key={o.id}><b>{o.title}</b><small>{o.priority}</small></button>)}</aside><OpportunityView o={current} sources={sources(current.sourceIds)} onSource={setSource} onScenario={()=>setArea('scenarios')} onExperiment={()=>setArea('experiments')}/></section>}
 {area==='evidence'&&<section className="page-section"><div className="section-head"><span>EVIDENCE WORKSPACE</span><h1>Observed facts, implications and limits.</h1><p>{new Set(baseline.signals.map((s:any)=>s.url)).size} baseline source URLs. User-added evidence stays unverified until review.</p></div><div className="evidence-grid">{baseline.signals.map((s:any)=><article key={s.id}><span>{s.relationship} · {s.dimension}</span><h3>{s.title}</h3><p>{s.fact}</p><button onClick={()=>setSource(investigation.sources.find(x=>x.id===s.id)||{...s,publisher:s.source,dateLabel:s.date})}><BookOpen/> Inspect source</button></article>)}</div><a className="library-link" href="/signals">Open saved reviews and add evidence <ExternalLink/></a></section>}
 {area==='scenarios'&&<section className="page-section"><div className="section-head"><span>HYPOTHETICAL · DOES NOT CHANGE RECORDED PRIORITIES</span><h1>How could a competitor respond?</h1><p>Scenario outputs are conditional comparisons, not forecasts or probabilities.</p></div><div className="scenario-layout"><aside className="scenario-select">{opportunities.map(o=><button className={selected===o.id?'active':''} onClick={()=>setSelected(o.id)} key={o.id}>{o.title}</button>)}</aside><article className="scenario-card"><label htmlFor="move">Competitor response</label><select id="move" value={scenario[current.id]||scenarioChoices[current.id][0]} onChange={e=>setScenario({...scenario,[current.id]:e.target.value})}>{scenarioChoices[current.id].map(x=><option key={x}>{x}</option>)}</select><div className="versus"><div><span>BASELINE</span><h3>{current.priority}</h3><p>{current.challenge}</p></div><div><span>UNDER THIS SCENARIO</span><h3>{current.scenario?.effect||'Differentiation weakens; investigate direct substitution.'}</h3><p><b>Changed assumption:</b> {current.scenario?.move||'A competitor can respond quickly.'}</p></div></div><h4>Response to examine</h4><p>{current.scenario?.response||'Compare against the direct incumbent and include no purchase.'}</p><Button onClick={()=>save('competitive_scenario',current.id,{opportunityId:current.id,move:scenario[current.id]||scenarioChoices[current.id][0],assumptions:['Competitor can execute this move','Prices shown are feasible'],response:current.scenario?.response||'',evidenceVersion:investigation.updatedAt})}><Save/> Save scenario</Button></article></div></section>}
 {area==='experiments'&&<section className="page-section"><div className="section-head"><span>PROPOSED · NOT YET RUN</span><h1>Test the decision, not the idea alone.</h1></div><div className="experiment-layout"><aside className="scenario-select">{opportunities.map(o=><button className={selected===o.id?'active':''} onClick={()=>{setSelected(o.id);setDraft(null)}} key={o.id}>{o.title}</button>)}</aside><article className="experiment-card"><h2>{current.experiment.title}</h2>{(['design','measure','stop'] as const).map((k,i)=><label key={k}><span>0{i+1} / {k==='measure'?'PRIMARY MEASURE':k.toUpperCase()}</span><Textarea rows={k==='design'?5:3} value={(draft||current.experiment)[k]} onChange={e=>setDraft({...current.experiment,...draft,[k]:e.target.value})}/></label>)}<div className="rules"><p><b>Advance:</b> {current.advance||'Set before launch.'}</p><p><b>Business threshold:</b> Set before launch</p></div><Button onClick={()=>save('experiment',current.id,{opportunityId:current.id,status:'proposed',...(draft||current.experiment),advance:current.advance||'Set before launch',threshold:'Set before launch',owner:'Unassigned'})}><Save/> Save proposed experiment</Button></article></div></section>}
 {area==='history'&&<section className="page-section"><div className="section-head"><span>RECORDED RESEARCH</span><h1>What changed—and what did not.</h1><p>Historical records without page ledgers remain labeled legacy. No audit rows have been invented.</p></div><div className="history-layout"><div>{baseline.runs.map((r:any,i:number)=><article className="run" key={i}><span>{fmt(r.date)} · {i===0?'RECORDED PASS':'LEGACY RECORD'}</span><h3>{r.sources} source pages</h3><p>{r.summary}</p></article>)}</div><aside><h2>Decision history</h2><article><Check/><div><b>Cat discovery bundle · priority held</b><p>Availability and promotion do not establish repeat purchase or incremental demand.</p></div></article>{investigation.revisions.map((r,i)=><article key={i}><History/><div><b>{r.after}</b><p>{r.reason}</p></div></article>)}<h2>Research queue</h2>{records.filter(r=>r.kind==='mission').map(r=><article key={r.id}><Clock3/><div><b>{r.data.question}</b><p>Queued · waiting for existing scheduled workflow</p></div></article>)}<Textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={3}/><Textarea value={context} onChange={e=>setContext(e.target.value)} rows={2} placeholder="Optional context"/><Button onClick={()=>save('mission',crypto.randomUUID(),{question,context,status:'queued'})}><Search/> Queue question</Button><p className="connection"><ShieldCheck/> {connected?'Immediate executor configured; successful operation is not asserted.':'Immediate research disabled: OPENAI_API_KEY is not configured. The existing external task remains the scheduler.'}</p></aside></div></section>}
 </main>
 {demoOn&&<div className="demo-controls"><button onClick={()=>goDemo(Math.max(0,demo!-1))} disabled={demo===0}><ChevronLeft/> Back</button><span>Step {demo!+1} of 5 · {demoSteps[demo!]}</span><button onClick={()=>demo===4?startDemo():goDemo(demo!+1)}>{demo===4?<><RefreshCw/> Restart</>:<>Next <ChevronRight/></>}</button></div>}
 {(error||notice)&&<div className={'engine-toast '+(error?'error':'')} role={error?'alert':'status'}>{error||notice}<button onClick={()=>{setError('');setNotice('')}} aria-label="Dismiss"><X/></button></div>}
 <Sheet open={!!source} onOpenChange={v=>!v&&setSource(null)}><SheetContent className="engine-drawer">{source&&<><SheetHeader><span className="eyebrow">SOURCE · VERIFIED HISTORICAL FIXTURE</span><SheetTitle>{source.title}</SheetTitle><SheetDescription>{source.publisher} · {source.dateLabel}</SheetDescription></SheetHeader><a href={source.url} target="_blank" rel="noopener noreferrer">Open direct source <ExternalLink/></a><h3>Observation</h3><p>{source.fact}</p><h3>Implication</h3><p>{source.implication}</p><h3>Limitation</h3><p>{source.limitation}</p></>}</SheetContent></Sheet>
 </div>;
}

function OpportunityView({o,sources,onSource,onScenario,onExperiment}:{o:Opportunity;sources:Source[];onSource:(s:Source)=>void;onScenario:()=>void;onExperiment:()=>void}){return <article className="op-detail"><span className="eyebrow">PROPOSED DECISION · {o.priority}</span><h1>{o.title}</h1><p className="lead">{o.proposition}</p><div className="decision-grid"><div><span>WHO HAS THE NEED</span><p>{o.who}</p></div><div><span>WHAT WE WOULD DO</span><p>{o.experiment.title}</p></div><div><span>WHY IT MAY WORK</span><p>{o.support}</p></div><div><span>WHY IT MAY FAIL</span><p>{o.challenge}</p></div></div><section><h2>Closest substitutes</h2><p>{o.substitutes}</p></section><section><h2>Evidence</h2><div className="source-row">{sources.map(s=><button onClick={()=>onSource(s)} key={s.id}><BookOpen/><span><b>{s.publisher}</b><small>{s.title}</small></span><ChevronRight/></button>)}</div></section><section className="unknown"><Swords/><div><h2>Largest unknown</h2><p>{o.unknown}</p></div></section><div className="op-actions"><Button onClick={onScenario}>Challenge with competitor response <ArrowRight/></Button><Button variant="outline" onClick={onExperiment}><FlaskConical/> Open proposed test</Button></div></article>}
